spin_manifest_version = "1"
authors = ["kanin-kearpimy <kanin.kearpimy@gmail.com>"]
description = "Handle game puzzle session for player."
name = "game-session"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "game-session"
source = "app.wasm"
[component.trigger]
route = "/sessions"
[component.build]
command = "spin py2wasm app -o app.wasm"
