spin_manifest_version = "1"
authors = ["kanin-kearpimy <kanin.kearpimy@gmail.com>"]
description = "Scoring"
name = "game-score"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "game-score"
source = "target/spin-http-js.wasm"
exclude_files = ["**/node_modules"]
environment = {REDIS_HOST = "redis://localhost:6379/"}
[component.trigger]
route = "/score"
[component.build]
command = "npm run build"
